name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # manually
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.8
        with:
          version: 11
          run_install: false

      - name: Set up Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: node
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install -r --ignore-scripts

      - name: Check formatting (Prettier)
        run: pnpm exec prettier -c .

      - name: Generate TypeScript types
        run: pnpm postbuild

      - name: Run type checks (TypeScript)
        run: pnpm tsc

      - name: Run linter (ESLint)
        run: pnpm lint
